# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  

  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.github.com/repos/Ashadevadiga/PracticeRepo/pulls \'
        method: 'POST'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"title":"Sample","body":"creating pull request using api!","head":"development","base":"main"}'
